### ISSUE TITLE
open source and free

### ISSUE THREAD

**Issue by dinarpay** [aliyazdi75/flutter_chat#3]
My friend
Is the app open source and free
What are the features of the application, is it like WhatsApp
Do I need a server and monthly fees to operate the voice and video chat service?

**Comment by aliyazdi75** [comment]
Yes, I believe all applications in the world must be open-source.
I told you, read the readme!
It uses webRTC, first, you should learn what webRTC is.
No, a simple socket server for handshaking would be enough.
