### ISSUE TITLE
MethodInvacationFunc NOT Found

### ISSUE THREAD

**Issue by Bhanupriya-Sharma** [aliyazdi75/flutter_chat#5]
I got this repo run in my system and it gave me the error that it didn't find the 'MethodInvacationFunc' type.

lib/services/signalR/src/helper.dart:14:9: Error: Type 'MethodInvacationFunc' not found.
  final MethodInvacationFunc methodFunction;
        ^^^^^^^^^^^^^^^^^^^^

I have given just one such place, but it pointed out all those places where 'MethodInvacationFunc' type is used.
Kindly tell, what is 'MethodInvacationFunc' type and how to curb this error?

**Comment by aliyazdi75** [comment]
Hi, you should `pub get` first. It's in the `signalr_core` package.

**Comment by Bhanupriya-Sharma** [comment]
I had already done Pub Get, I even updated the singalr_core dependency
version to ^1.1.1.
It is still reacting the same way, not able to find the
*MethodInvacationFunc*.
It cannot also not find the *responseCallBack* function as well as the
variable *arguments* doesn't have a type. All this is only in
*lib/services/signalR/src/helper.dart* file.

**Comment by aliyazdi75** [comment]
yes, you are right, in the new version of this package that keyword changed from `MethodInvacationFunc` to `MethodInvocationFunc`.
https://github.com/jamiewest/signalr_core/blob/main/lib/src/hub_connection.dart#L13
I will fix that later, but you can change it in your project and fix that problem.
