### ISSUE TITLE
is this doesn't wok for flutter web?

### ISSUE THREAD

**Issue by hanafiahtkj** [aliyazdi75/flutter_chat#8]
i just try this in web flutter but doest work.

**Comment by aliyazdi75** [comment]
It shouldn't be working! You need a server for that.

**Comment by hanafiahtkj** [comment]
i mean run/debug this in we browser. not in device or android emulator, but if i debug this  in android device, it work correcly. i think there are a package that doesnt work in flutter web

**Comment by aliyazdi75** [comment]
All packages support the web. What is your log? I can run it fine.

**Comment by hanafiahtkj** [comment]
I run it in flutlab. Flutlab just have web emulator. No error' message 😓.

But if i build to android. Then install apk in my device. It perfecly fine.

**Comment by aliyazdi75** [comment]
I don't know what's that. just try flutter run

**Comment by hanafiahtkj** [comment]
FlutLab is a modern Flutter online IDE, i have no laptop with enough Spec to run Android studio or vs code 😓

**Comment by aliyazdi75** [comment]
Sorry, I can't help you with that tool.
